### ISSUE TITLE
proxmox helper scripts combing

### ISSUE THREAD

**Issue by tallguyjenks** [Bryan-Jenks-Home-Lab/TODO#22]
- [x] https://github.com/tteck/Proxmox
---
- [x] PostgreSQL LXC
- [x] InfluxDB/Telegraf LXC
- [x] ❗️Docker LXC
- [x] UniFi Network Application LXC 
  - can this be used to make my own way of displaying unifi protect instead of needing the viewport?
- [x] Plex Media Server LXC related to #9 
- [x] Pi-hole LXC #24 [pi-hole video](https://youtu.be/FnFtWsZ8IP0)
- [x] ❓️ Technitium DNS LXC #24 
- [x] Uptime Kuma LXC
- [x] Whoogle LXC
- [x] Dashy LXC (potential replacement for heimdall?)
- [x] grocy LXC Grocery management solution? 🤣 
- [x] ❓️Daemon Sync Server LXC
- [x] File Browser related to #18 
- [x] VS Code Server
- [x] Webmin System Administration
- [x] keycloak LXC
